
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(1, 1, 1, 1, 1, '2014-09-01 00:00:00', '2014-09-30 00:00:00', 'Secretaria Ejecutiva', 'No disponible', '2013.N.0009', 'IFAI/SPDP/DGV/063/2013', 'IFAI/SG/DGCPRI/045/2013', 'PARTICIPAR EN LA REUNION DE LA REGION NORTE DE LA CONFERENCIA MEXICANA PARA EL ACCESO A LA INFORMACION PUBLICA (COMAIP) REUNION DE LA COMISION DE GESTION DOCUMENTAL TECNOLOGIAS DE LA INFORMACION Y GOBIERNO ABIERTO DE LA CONFERENCIA MEXICANA PARA EL ACCESO A LA INFORMACION PUBLICA (COMAIP) Y EN EL PRIMER FORO NACIONAL DE ANALISIS Y REFLEXION SOBRE LA REFORMA CONSTITUCIONAL EN MATERIA DE TRANSPARENCIA Y ACCESO A LA INFORMACION PUBLICA EN MEXICO ORGANIZADO POR LA CONFERENCIA MEXICANA PARA EL ACCESO A LA INFORMACION PUBLICA (COMAIP).', 1300.00, 0.00, 64.00, 'Se renovaron los coordinadores de la Region Norte de la COMAIP', 'No aplica', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(2, 2, 1, 3, 2, '2014-09-02 00:00:00', '2014-10-04 00:00:00', 'Casa del Migrante de Saltillo', 'Direccion General de Capacitacion Promocion Relaciones Institucionales', '2013.N.0010', 'No disponible', 'IFAI/SG/DGCPRI/045/2014', 'COORDINAR LA PARTICIPACION DEL COMISIONADO PRESIDENTE DEL IFAI EN EL FORO NACIONAL DE ANALIS Y REFLEXION SOBRE LA REFORMA CONSTITUCIONAL EN MATERIA DE TRANSPARENCIA Y ACCESO A LA INFORMACION PUBLICA EN MEXICO ORGANIZADA POR LA COMISION ESTATAL PARA LA TRANSPARENCIA Y EL ACCESO A LA INFORMACION PUBLICA DE DurANGO Y LA CONFERENCIA MEXICANA PARA EL ACCESO A LA INFORMACION PUBLICA (COMAIP).', 1500.00, 929.00, 125.00, 'Inferir en analisis de los recursos', 'No aplica', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(3, 3, 1, 3, 2, '2014-09-03 00:00:00', '2014-10-05 00:00:00', 'Secretaria de Proteccion de Datos', 'Direccion General de Capacitacion Promocion Relaciones Institucionales', '2013.N.0011', 'IFAI/SPADP/DGV/063/2014', 'IFAI/SG/DGCPRI/045/2015', 'PARTICIPAR EN LA PRIMERA JORNADA DE CAPACITACION PARA PRESIDENTES MUNICIPALES SOBRE LA IMPORTANCIA DE LA RENDICION DE CUENTAS Y LA TRANSPARENCIA EN LOS MUNICIPIOS ORGANIZADA POR EL INSTITUTO NACIONAL PARA EL FEDERALISMO Y EL DESARROLLO MUNICIPAL Y EL GOBIERNO DEL ESTADO DE PUEBLA.', 7500.00, 4.00, 3285.00, 'Se renovaron los coordinadores de la Region Norte de la COMAIP', 'No aplica', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(4, 4, 2, 2, 1, '2014-09-04 00:00:00', '2014-09-22 00:00:00', 'Conferencia Internacional de Autoridades de Proteccion de Datos y Privacidad', 'Instituto de tecnologia', '2013.N.0012', 'IFAI/SPADP/DGV/063/2015', 'IFAI/SG/DGCPRI/045/2016', 'PARTICIPAR EN LA PRIMERA JORNADA DE CAPACITACION PARA PRESIDENTES MUNICIPALES SOBRE LA IMPORTANCIA DE LA RENDICION DE CUENTAS Y LA TRANSPARENCIA EN LOS MUNICIPIOS ORGANIZADA POR EL INSTITUTO NACIONAL PARA EL FEDERALISMO Y EL DESARROLLO MUNICIPAL Y EL GOBIERNO DEL ESTADO DE PUEBLA.', 900.00, 789.00, 55.00, 'No aplica', 'No aplica', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(5, 5, 1, 3, 1, '2014-09-05 00:00:00', '2014-09-23 00:00:00', 'DIRECCION GENERAL DE CAPACITACION PROMOCION Y RELACIONES INSTITUCIONALES', 'Direccion para el fomento educativo', '2013.N.0013', 'IFAI/SPADP/DGV/063/2016', 'IFAI/SG/DGCPRI/045/2017', 'SEGUIMIENTO AL EXPEDIENTE DEL AMPARO EN REVISION NUMERO 299/2012 INSTAurADA POR EL SINDICATO DE TRABAJADORES PETROLEROS DE LA REPUBLICA MEXICANA DEL INDICE DEL QUINTO TRIBUNAL COLEGIADO DEL CENTRO AUXILIAR DE LA TERCERA REGION CON SEDE EN MORELIA MICHOACAN.', 10000.00, 5455.00, 515.00, 'Inferir en analisis de los recursos', 'Se limitaron los tiempos', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(6, 6, 2, 3, 2, '2014-09-06 00:00:00', '2014-09-24 00:00:00', 'El Presidente del Consejo para la Transparencia extendia', 'No disponible', '2013.N.0014', 'IFAI/SPADP/DGV/063/2017', 'IFAI/SG/DGCPRI/045/2018', 'PARTICIPAR EN LA REUNION DE LA REGION NORTE DE LA CONFERENCIA MEXICANA PARA EL ACCESO A LA INFORMACION PUBLICA (COMAIP) REUNION DE LA COMISION DE GESTION DOCUMENTAL. TECNOLOGIAS DE LA INFORMACION Y GOBIERNO ABIERTO DE LA CONFERENCIA MEXICANA PARA EL ACCESO A LA INFORMACION PUBLICA (COMAIP) Y EN EL PRIMER FORO NACIONAL DE ANALISIS Y REFLEXION SOBRE LA REFORMA CONSTITUCIONAL EN MATERIA DE TRANSPARENCIA Y ACCESO A LA INFORMACION PUBLICA EN MEXICO ORGANIZADO POR LA CONFERENCIA MEXICANA PARA EL ACCESO A LA INFORMACION PUBLICA (COMAIP).', 5621.00, 547.00, 951.00, 'Renovar las tecnologias', 'No se obtuvo un retroalimentacion', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(7, 7, 1, 3, 1, '2014-09-07 00:00:00', '2014-09-25 00:00:00', 'Secretariaa General', 'Direccion Autonoma de Tecnologiaa', '2013.N.0015', 'IFAI/SPADP/DGV/063/2018', 'IFAI/SG/DGCPRI/045/2019', 'COORDINAR LA PARTICIPACION DEL COMISIONADO PRESIDENTE DEL IFAI EN EL FORO NACIONAL DE ANALIS Y REFLEXION SOBRE LA REFORMA CONSTITUCIONAL EN MATERIA DE TRANSPARENCIA Y ACCESO A LA INFORMACION PUBLICA EN MEXICO ORGANIZADA POR LA COMISION ESTATAL PARA LA TRANSPARENCIA Y EL ACCESO A LA INFORMACION PUBLICA DE DurANGO Y LA CONFERENCIA MEXICANA PARA EL ACCESO A LA INFORMACION PUBLICA (COMAIP).', 891.00, 25.00, 136.00, 'Dar a conocer el del derecho constitucional', 'Se cancelaron ponencias', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(8, 8, 1, 3, 1, '2014-09-08 00:00:00', '2014-09-26 00:00:00', 'Universidad Autonoma de Puebla', 'Gerencia Nacional de comercio', '2013.N.0016', 'No disponible', 'IFAI/SG/DGCPRI/045/2020', 'PARTICIPAR EN LA PRIMERA JORNADA DE CAPACITACION PARA PRESIDENTES MUNICIPALES SOBRE LA IMPORTANCIA DE LA RENDICION DE CUENTAS Y LA TRANSPARENCIA EN LOS MUNICIPIOS ORGANIZADA POR EL INSTITUTO NACIONAL PARA EL FEDERALISMO Y EL DESARROLLO MUNICIPAL Y EL GOBIERNO DEL ESTADO DE PUEBLA.', 232.00, 858.00, 0.00, 'Generar fuentes de informacion', 'No aplica', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(9, 9, 1, 2, 1, '2014-09-09 00:00:00', '2014-09-12 00:00:00', 'Canacintra', 'Instituto de tecnologia', '2013.N.0017', 'No disponible', 'IFAI/SG/DGCPRI/045/2021', 'PARTICIPAR EN LA PRIMERA JORNADA DE CAPACITACION PARA PRESIDENTES MUNICIPALES SOBRE LA IMPORTANCIA DE LA RENDICION DE CUENTAS Y LA TRANSPARENCIA EN LOS MUNICIPIOS ORGANIZADA POR EL INSTITUTO NACIONAL PARA EL FEDERALISMO Y EL DESARROLLO MUNICIPAL Y EL GOBIERNO DEL ESTADO DE PUEBLA.', 7892.00, 376.00, 320.00, 'No aplica', 'No aplica', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(10, 10, 2, 3, 2, '2014-09-10 00:00:00', '2014-09-13 00:00:00', 'No disponible', 'Institutito de la camara de comercio', '2013.N.0018', 'No disponible', 'IFAI/DGAJ/055/13', 'SEGUIMIENTO AL EXPEDIENTE DEL AMPARO EN REVISION NUMERO 299/2012 INSTAurADA POR EL SINDICATO DE TRABAJADORES PETROLEROS DE LA REPUBLICA MEXICANA DEL INDICE DEL QUINTO TRIBUNAL COLEGIADO DEL CENTRO AUXILIAR DE LA TERCERA REGION CON SEDE EN MORELIA MICHOACAN.', 1200.00, 461.00, 0.00, 'No aplica', 'No aplica', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(11, 11, 1, 1, 2, '2014-09-11 00:00:00', '2014-09-24 00:00:00', 'Direccion Genereal de Verificacion', 'Oficina del comisionado ATZ', '2013.N.0019', 'No disponible', 'IFAI/DGAJ/055/14', 'IMPARTIR CONFERENCIA MAGISTRAL EN EL MARCO DEL DIA INTERNACIONAL DE LA PROTECCION DE DATOS PERSONALES.', 4945.00, 0.00, 0.00, 'Se renovaron los coordinadores de la Region Norte de la COMAIP', 'No aplica', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(12, 12, 1, 3, 2, '2014-09-12 00:00:00', '2014-09-25 00:00:00', 'Direccion Genereal de Verificacion', 'Presidencia', '2013.N.0020', 'IFAI/SPADP/DGV/063/2023', 'IFAI/DGAJ/055/15', 'PARTICIPAR COMO PANELISTA EN EL SEGUNDO FORO NACIONAL DE TRANSPARENCIA Y DATOS PERSONALES DE SALUD QUE ORGANIZA EL HOSPITAL CIVIL DE GUADALAJARA.', 9834.00, 1567.00, 55.00, 'No aplica', 'Se limitaron los tiempos', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(13, 13, 1, 3, 1, '2014-09-13 00:00:00', '2014-10-04 00:00:00', 'Direccion General de Asuntos Juridicos', 'Camara de diputados', '2013.N.0021', 'IFAI/SPADP/DGV/063/2024', 'IFAI/DGAJ/055/16', 'ASISTIR A LA REUNION ORDINARIA DE LA COMISION JurIDICA DE LA CONFERENCIA MEXICANA PARA EL ACCESO A LA INFORMACION PUBLICA (COMAIP).', 4652.00, 1464.00, 2551.00, 'No aplica', 'No se obtuvo un retroalimentacion', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(14, 14, 2, 5, 1, '2014-09-14 00:00:00', '2014-10-05 00:00:00', 'Instituto de Transparencia y Acceso a la Informacion Publica del Estado de Nayarit', 'Seneado de la republica', '2013.N.0022', 'IFAI/SPADP/DGV/063/2025', 'No disponible', 'LA COMISION SE REALIZO CON EL OBJETO DE DAR SEGUIMIENTO AL JUICIO CONTENCIOSO ADMINISTRATIVO FEDERAL 1789/12-03-01-3/41/13-TSA-6 INTERPUESTO POR OPERADORA OCEANICA INTERNACIONAL S.A. DE C.V. EN CONTRA DE ESTE INSTITUTO. DICHO JUICIO SE ENCUENTRA RADICADO EN LA TERCERA SALA AUXILIAR CON SEDE EN TORREON COAHUILA DEL TRIBUNAL FEDERAL DE JUSTICIA FISCAL Y ADMINISTRATIVA.', 830.00, 467.00, 0.00, 'No aplica', 'Se cancelaron ponencias', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(15, 15, 1, 2, 2, '2014-09-15 00:00:00', '2014-10-06 00:00:00', 'IACIP', 'Delegacion de central de escuelas', '2013.N.0023', 'IFAI/SPADP/DGV/063/2026', 'IFAI/SG/DGCPRI/037/2013', '"DERIVADO DE LA SOLICITUD DE CAPACITACION QUE REALIZO AL IFAI LA CASA DEL MIGRANTE DE SALTILLO A TRAVES DE LA RED NACIONAL "TODOS LOS DERECHOS PARA TODAS Y TODOS" IMPARTIR UN TALLER DE CAPACITACION SOBRE EL DERECHO DE PROTECCION DE DATOS PERSONALES EN POSESION DE PARTICULARES A INTEGRANTES DE ORGANIZACIONES DE LA SOCIEDAD CIVIL EN SALTILLO COAHUILA EL 29 DE ENERO DEL 2013."', 8.00, 96.00, 0.00, 'No aplica', 'No aplica', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(16, 16, 2, 4, 1, '2014-09-16 00:00:00', '2014-10-07 00:00:00', 'Direccion General de Capacitacion Promocion y Relaciones Institucionales', 'SEP', '2013.N.0024', 'IFAI/SPADP/DGV/063/2027', 'IFAI/SG/DGCPRI/037/2014', '"DERIVADO DE LA SOLICITUD DE CAPACITACION QUE REALIZO AL IFAI LA CASA DEL MIGRANTE DE SALTILLO A TRAVES DE LA RED NACIONAL "TODOS LOS DERECHOS PARA TODAS Y TODOS" IMPARTIR UN TALLER DE CAPACITACION SOBRE EL DERECHO DE PROTECCION DE DATOS PERSONALES EN POSESION DE PARTICULARES A INTEGRANTES DE ORGANIZACIONES DE LA SOCIEDAD CIVIL EN SALTILLO COAHUILA EL 29 DE ENERO DEL 2013."', 463.00, 961.00, 55.00, 'No aplica', 'No aplica', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(17, 17, 1, 3, 1, '2014-09-17 00:00:00', '2014-10-08 00:00:00', 'eCOM-LAC', 'SEGOB', '2013.N.0025', 'IFAI/SPADP/DGV/063/2028', 'IFAI/SG/DGCPRI/037/2015', '"PARTICIPAR EN EL X ENCUENTRO IBEROAMERICANO DE PROTECCION DE DATOS PERSONALES Y EN LA ""34A. CONFERENCIA INTERNACIONAL DE AUTORIDADES DE PROTECCION DE DATOS Y PRIVACIDAD"" QUE TENDRA LUGAR DEL 22 AL 26 DE OCTUBRE DE 2012 EN PUNTA DEL ESTE urUGUAY. VIAJE CANCELADO"', 892.00, 57.00, 145.00, 'Superar las metas propuestas', 'No aplica', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(18, 18, 2, 3, 2, '2014-09-18 00:00:00', '2014-09-25 00:00:00', 'CEFAB', 'SETRAVI', '2013.N.0026', 'IFAI/SPADP/DGV/063/2029', 'IFAI/SG/DGCPRI/037/2016', '"APOYAR Y COORDINAR LA PARTICIPACION DEL COMISINADO DEL IFAI EN LA CONFERENCIA MAGISTRAL "LA PROTECCION DE LOS DATOS PERSONALES. EL NUEVO RETO" EN EL MARCO DEL DIA INTERNACIONAL DE LA PROTECCION DE DATOS PERSONALES ORGANIZADO POR EL INSTITUTO DE ACCESO A LA INFORMACION PUBLICA GUBERNAMENTAL DEL ESTADO DE HIDALGO."', 655.00, 671.00, 95.00, 'Dar a conocer los resultados obtenidos', 'No aplica', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(19, 19, 1, 3, 2, '2014-09-19 00:00:00', '2014-09-25 00:00:00', 'Direccion General de Capacitacion Promocion y Relaciones Institucionales', 'Presidencia', '2013.N.0027', 'IFAI/SPADP/DGV/063/2030', 'IFAI/SG/DGCPRI/039/2014', '"PRESIDIR EL V ENCUENTRO DE LA RED DE TRANSPARENCIA Y ACCESO A LA INFORMACION (RTA) ASI COMO PARTICIPAR EN EL SEMINARIO INTERNACIONAL 2013 DEL DICHO AL HECHO DEL DISCurSO PUBLICO A LA ACCION" AMBOS EVENTOS ORGANIZADOS POR EL CONSEJO PARA LA TRANSPARENCIA DE CHILE."', 9253.00, 641.00, 351.00, 'No aplica', 'No aplica', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(20, 20, 2, 2, 2, '2014-09-20 00:00:00', '2014-09-26 00:00:00', 'Organo Interno de Control', 'Secretaria de Bellas Artes', '2013.N.0028', 'IFAI/SPADP/DGV/063/2031', 'IFAI/SG/044/2013', '"CurSAR EL SEGUNDO SEMESTRE DE LA MAESTRIA DE GESTION DOCUMENTAL Y ADMINISTRACION DE ARCHIVOS QUE SE IMPARTE EN LA UNIVERSIDAD DE LA SALLE EN LA CIUDAD DE BOGOTA COLOMBIA EN EL MARCO DEL CONVENIO DE APORTACION DE RECurSOS QUE CELEBRAN EL CONSEJO NACIONAL DE CIENCIA Y TECNOLOGIA ""CONACYT"" Y EL ARCHIVO GENERAL DE LA NACION ""AGN""."', 1328.00, 0.00, 105.00, 'No aplica', 'No aplica', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(21, 21, 1, 3, 2, '2014-09-21 00:00:00', '2014-09-25 00:00:00', 'Dirreccion General de Capacitacion Promociones y Relaciones Institucionales', 'Presidencia', '2013.N.0029', 'IFAI/SPADP/DGV/063/2032', 'IFAI/DTP/GLR/008/2013', '"CurSAR EL SEGUNDO SEMESTRE DE LA MAESTRIA DE GESTION DOCUMENTAL Y ADMINISTRACION DE ARCHIVOS QUE SE IMPARTE EN LA UNIVERSIDAD DE LA SALLE EN LA CIUDAD DE BOGOTA COLOMBIA EN EL MARCO DEL CONVENIO DE APORTACION DE RECurSOS QUE CELEBRAN EL CONSEJO NACIONAL DE CIENCIA Y TECNOLOGIA ""CONACYT"" Y EL ARCHIVO GENERAL DE LA NACION ""AGN""."', 598.00, 31.00, 3085.00, 'No aplica', 'No aplica', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(22, 22, 1, 2, 2, '2014-09-22 00:00:00', '2014-09-25 00:00:00', 'Direccion General de Capacitacion Promocion y Relaciones Institucionales', 'Senado de la republica', '2013.N.0030', 'IFAI/SPADP/DGV/063/2033', 'IFAI/SG/DGCPRI/239/2013', 'CAPACITAR A LAS EMPRESAS ASOCIADAS A LA CANACINTRA PUEBLA EN MATERIA DE LA LEY FEDERAL DE PROTECCION DE DATOS PERSONALES EN POSESION DE LOS PARTICULARES A TRAVES DE UN CurSO PRESENCIAL DE 5 HORAS.', 204.00, 651.00, 51.00, 'No aplica', 'No aplica', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(23, 23, 1, 3, 1, '2014-09-23 00:00:00', '2014-09-24 00:00:00', 'Direccion General de Comunicaci', 'Gerencia de arte', '2013.N.0031', 'IFAI/SPADP/DGV/063/2034', 'IFAI/SG/DGCPRI/216/2013', 'PARTICIPAR EN LA REUNION DE COORDINACION CON SERVIDORES PUBLICOS DEL IFAI PARA LA LOGISTICA DE LA XIV ASAMBLEA PLENARIA DE LA CONFERENCIA MEXICANA PARA EL ACCESO A LA INFORMACION PUBLICA (COMAIP)', 8560.00, 7.00, 254.00, 'No aplica', 'No se consiguieron los resultados esperados', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(24, 24, 2, 5, 2, '2014-09-24 00:00:00', '2014-09-25 00:00:00', 'Direccion General de Capacitacion Promocion y Relaciones Institucionales', 'Instituto de tecnologia', '2013.N.0032', 'IFAI/SPADP/DGV/063/2035', 'IFAI/SG/DGCPRI/216/2014', 'Asistir a la L Reunion Naiconal de la Comision Nacional Permanente de Contralores Estado Federacion', 98.00, 47.00, 55.00, 'Se renovaron los coordinadores de la Region Norte de la COMAIP', 'Se deberia realizar cada 3 meses', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(25, 25, 2, 5, 1, '2014-09-25 00:00:00', '2014-09-25 00:00:00', 'Organo Interno de Control', 'No disponible', '2013.N.0033', 'IFAI/SPADP/DGV/063/2036', 'IFAI/DGAJ/0210/2012', 'ASISTIR A LA FERIA NACIONAL DEL LIBRO PARA PROMOVER Y DIFUNDIR EL EJERCICIO DEL DERECHO DE ACCESO A LA INFORMACION Y PROTECCION DE DATOS PERSONALES A TRAVES DE LA ORIENTACION ASESORIA Y ENTREGA DE MATERIALES DE DIVULGACION A LAS PERSONAS QUE ASISTAN AL MODULO ITINERANTE DEL CENTRO DE ATENCION A LA SOCIEDAD DEL IFAI QUE SE INSTAurARA EN DICHO EVENTO.', 8512.00, 51.00, 936.00, 'No aplica', 'No se consiguio el fuorum necesario', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(26, 26, 2, 2, 2, '2014-09-26 00:00:00', '2014-09-26 00:00:00', 'Dirreccion General de Capacitacion Promociones y Relaciones Institucionales', 'Direccion General de Asuntos Juridicos', '2013.N.0034', 'No disponible', 'IFAI/DGAJ/0210/2013', 'ASISTIR A LA FERIA NACIONAL DEL LIBRO PARA PROMOVER Y DIFUNDIR EL EJERCICIO DEL DERECHO DE ACCESO A LA INFORMACION Y PROTECCION DE DATOS PERSONALES A TRAVES DE LA ORIENTACION ASESORIA Y ENTREGA DE MATERIALES DE DIVULGACION A LAS PERSONAS QUE ASISTAN AL MODULO ITINERANTE DEL CENTRO DE ATENCION A LA SOCIEDAD DEL IFAI QUE SE INSTAurARA EN DICHO EVENTO.', 103.00, 913.00, 0.00, 'No aplica', 'No aplica', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(27, 27, 1, 3, 1, '2014-09-27 00:00:00', '2014-09-27 00:00:00', 'Direccion General de Capacitacion Promocion y Relaciones Institucionales', '"Direccion General de Capacitacion', ' Promocion y Relaciones Institucionales"', '2013.N.0035', 'No disponible', 'IFAI/SG/DGCPRI/274/2013', 0.00, 556.00, 3.00, '0', 'Se renovaron los coordinadores de la Region Norte de la COMAIP', 'N');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(28, 28, 1, 4, 1, '2014-09-28 00:00:00', '2014-09-28 00:00:00', 'Direccion General de Comunicaci', '"Direccion General de Normatividad', ' Consulta y Atencion Regional"', '2013.N.0036', 'No disponible', 'No disponible', 0.00, 743.00, 41.00, '15', 'No aplica', 'N');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(29, 29, 2, 1, 1, '2014-09-29 00:00:00', '2014-09-29 00:00:00', 'Dirreccion General de Capacitacion Promociones y Relaciones Institucionales', 'Direccion General de Capacitacion Promocion y Relaciones Institucionales', '2013.N.0037', 'IFAI/SPADP/DGV/063/2040', 'No disponible', 'REALIZAR COBERTurA DE PARTICIPACION DEL COMISIONADO PRESIDENTE GERARDO LAVEAGA R. EN EL 1er ANIVERSARIO DE LA LEY FEDERAL DE PROTECCION DE DATOS PERSONALES EN POSESION DE LOS PARTICULARES', 5543.00, 97.00, 85.00, 'No aplica', 'No aplica', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(30, 30, 1, 3, 2, '2014-09-30 00:00:00', '2014-09-30 00:00:00', 'Direccion General de Capacitacion Promocion y Relaciones Institucionales', 'Oficina del Comisionado Presidente', '2013.N.0038', 'IFAI/SPADP/DGV/063/2041', 'No disponible', 'PARTICIPAR COMO PONENETE EN EL FORO LATINOAMERICANO DE TELECOMUNICACIONES TECNOLOGIA Y POLITICAS PUBLICAS DE INTERNET', 913.00, 64.00, 9.00, 'No aplica', 'No aplica', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(31, 31, 1, 5, 1, '2014-10-01 00:00:00', '2014-10-01 00:00:00', 'Direccion General de Comunicaci', 'Direccion General de Capacitacion Promocion y Relaciones Institucionales', '2013.N.0039', 'IFAI/SPADP/DGV/063/2042', 'IFAI/SG/DGCPRI/323/2013', 'CAPACITAR A LAS INSTITUCIONES ASOCIADAS AL CONSEJO ESTATAL PARA EL FOMENTO A LAS ACTIVIDADES DE BIENESTAR Y DESARROLLO SOCIAL DEL  ESTADO DE BAJA CALIFORNIA EN MATERIA DE LA LEY FEDERAL DE PROTECCION DE DATOS PERSONALES EN POSESION DE LOS PARTICULARES A TRAVES DE UN CurSO PRESENCIAL DE 5 HORAS', 26.00, 11.00, 51.00, 'No aplica', 'No aplica', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(32, 32, 2, 4, 1, '2014-10-02 00:00:00', '2014-10-02 00:00:00', 'Direccion General de Capacitacion Promocion y Relaciones Institucionales', 'Direccion General de Capacitacion Promocion y Relaciones Institucionales', '2013.N.0040', 'IFAI/SPADP/DGV/063/2043', 'IFAI/SG/DGCPRI/364/2013', 'PARTICIPAR EN LA REUNION DE COORDINACION CON SERVIDORES PUBLICOS DEL IFAI PARA LA LOGISTICA DE LA XIV ASAMBLEA PLENARIA DE LA CONFERENCIA MEXICANA PARA EL ACCESO A LA INFORMACION PUBLICA (COMAIP)', 1596.00, 0.00, 7.00, 'No aplica', 'No aplica', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(33, 33, 2, 1, 2, '2014-10-03 00:00:00', '2014-10-03 00:00:00', 'Organo Interno de Control', 'Organo Interno de Control', '2013.N.0041', 'IFAI/SPADP/DGV/063/2044', 'IFAI/OIC/068/2013', 'Asistir a la L Reunion Naiconal de la Comision Nacional Permanente de Contralores Estado Federacion', 3258.00, 0.00, 458.00, 'Se renovaron los coordinadores de la Region Norte de la COMAIP', 'No aplica', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(34, 34, 2, 1, 1, '2014-10-04 00:00:00', '2014-10-04 00:00:00', 'Dirreccion General de Capacitacion Promociones y Relaciones Institucionales', 'Dirreccion General de Capacitacion Promociones y Relaciones Institucionales', '2013.N.0042', 'IFAI/SPADP/DGV/063/2045', 'IFAI/SG/DGCPRI/363/2013', 'ASISTIR A LA REUNION CON PERSONAL DEL (INFOEM) CON EL FIN DE REALIZAR LOS PREPARATIVOS DE LOGISTICA RUMBO A LA CELEBRACION DE LA XIV ASAMBLEA GENERAL DE LA (COMAIP)', 102.00, 114.00, 0.00, 'No aplica', 'No aplica', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(35, 35, 2, 1, 2, '2014-10-05 00:00:00', '2014-10-05 00:00:00', 'Direccion General de Capacitacion Promocion y Relaciones Institucionales', 'Direccion General de Capacitacion Promocion y Relaciones Institucionales', '2013.N.0043', 'IFAI/SPADP/DGV/063/2046', 'IFAI/SG/DGCPRI/263/2013', '"ASISTIR AL SEPTIMO FORO DE ANALISIS ""LA REFORMA CONSTITUCIONAL EN MATERIA DE TRANSPARENCIA Y ACCESO A LA INFORMACION PUBLICA EN MEXICO"""', 302.00, 747.00, 0.00, 'No aplica', 'No aplica', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(36, 36, 2, 2, 1, '2014-10-06 00:00:00', '2014-10-06 00:00:00', 'Direccion Central de Instituciones', 'Direccion de comunicaci', '2013.N.0044', 'IFAI/SPADP/DGV/063/2047', 'IFAI/SG/DGCPRI/263/2014', 'REALIZAR COBERTurA DE PARTICIPACION DEL COMISIONADO PRESIDENTE GERARDO LAVEAGA R. EN EL 1er ANIVERSARIO DE LA LEY FEDERAL DE PROTECCION DE DATOS PERSONALES EN POSESION DE LOS PARTICULARES', 0.00, 997.00, 0.00, 'No aplica', 'No aplica', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(37, 37, 2, 2, 2, '2014-10-08 00:00:00', '2014-10-01 00:00:00', 'Direccion General de Asuntos Juridicos', 'DIF', '2013.N.0045', 'IFAI/SPADP/DGV/063/2048', 'IFAI/SG/DGCPRI/263/2015', 'PARTICIPAR EN LA PRIMERA JORNADA DE CAPACITACION PARA PRESIDENTES MUNICIPALES SOBRE LA IMPORTANCIA DE LA RENDICION DE CUENTAS Y LA TRANSPARENCIA EN LOS MUNICIPIOS ORGANIZADA POR EL INSTITUTO NACIONAL PARA EL FEDERALISMO Y EL DESARROLLO MUNICIPAL Y EL GOBIERNO DEL ESTADO DE PUEBLA.', 56.00, 1000.00, 85.00, 'Generar fuentes de informacion', 'Todo salio correctamente', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(38, 38, 1, 3, 1, '2014-09-25 00:00:00', '2014-10-02 00:00:00', 'Instituto de Transparencia y Acceso a la Informacion Publica del Estado de Nayarit', 'IMSS', '2013.N.0046', 'No disponible', 'IFAI/SG/DGCPRI/263/2016', 'PARTICIPAR EN LA PRIMERA JORNADA DE CAPACITACION PARA PRESIDENTES MUNICIPALES SOBRE LA IMPORTANCIA DE LA RENDICION DE CUENTAS Y LA TRANSPARENCIA EN LOS MUNICIPIOS ORGANIZADA POR EL INSTITUTO NACIONAL PARA EL FEDERALISMO Y EL DESARROLLO MUNICIPAL Y EL GOBIERNO DEL ESTADO DE PUEBLA.', 0.00, 447.00, 943.00, 'Solicitar recursos para el herario', 'Fue un comit', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(39, 39, 1, 5, 2, '2014-09-25 00:00:00', '2014-10-05 00:00:00', 'IACIP', 'ISSSTE', '2013.N.0047', 'No disponible', 'IFAI/SG/DGCPRI/263/2017', 'SEGUIMIENTO AL EXPEDIENTE DEL AMPARO EN REVISION NUMERO 299/2012 INSTAurADA POR EL SINDICATO DE TRABAJADORES PETROLEROS DE LA REPUBLICA MEXICANA DEL INDICE DEL QUINTO TRIBUNAL COLEGIADO DEL CENTRO AUXILIAR DE LA TERCERA REGION CON SEDE EN MORELIA MICHOACAN.', 66.00, 1056.00, 9.00, 'Determinar las causas que originan lo obtenido', 'Se deberia realizar mas seguido', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(40, 40, 2, 5, 1, '2014-09-27 00:00:00', '2014-10-04 00:00:00', 'Direccion General de Capacitacion Promocion y Relaciones Institucionales', 'SETRAVI', '2013.N.0048', 'No disponible', 'No disponible', 'LA COMISION SE REALIZO CON EL OBJETO DE DAR SEGUIMIENTO AL JUICIO CONTENCIOSO ADMINISTRATIVO FEDERAL 1789/12-03-01-3/41/13-TSA-6 INTERPUESTO POR OPERADORA OCEANICA INTERNACIONAL S.A. DE C.V. EN CONTRA DE ESTE INSTITUTO. DICHO JUICIO SE ENCUENTRA RADICADO EN LA TERCERA SALA AUXILIAR CON SEDE EN TORREON COAHUILA DEL TRIBUNAL FEDERAL DE JUSTICIA FISCAL Y ADMINISTRATIVA.', 87.00, 4.00, 2.00, 'Centrarse en fuentes de informacion veridicas', 'No se consiguieron los resultados esperados', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(41, 41, 2, 2, 2, '2014-09-28 00:00:00', '2014-10-05 00:00:00', 'eCOM-LAC', 'SEGOB', '2013.N.0049', 'No disponible', 'No disponible', '"DERIVADO DE LA SOLICITUD DE CAPACITACION QUE REALIZO AL IFAI LA CASA DEL MIGRANTE DE SALTILLO A TRAVES DE LA RED NACIONAL ""TODOS LOS DERECHOS PARA TODAS Y TODOS"" IMPARTIR UN TALLER DE CAPACITACION SOBRE EL DERECHO DE PROTECCION DE DATOS PERSONALES EN POSESION DE PARTICULARES A INTEGRANTES DE ORGANIZACIONES DE LA SOCIEDAD CIVIL EN SALTILLO COAHUILA EL 29 DE ENERO DEL 2013."', 0.00, 774.00, 0.00, 'Permanecer en el contenido', 'Se deberia realizar cada 3 meses', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(42, 42, 1, 3, 1, '2014-09-29 00:00:00', '2014-10-06 00:00:00', 'CEFAB', 'PGR', '2013.N.0050', 'IFAI/SPADP/DGV/063/2041', 'No disponible', 'SEGUIMIENTO AL EXPEDIENTE DEL AMPARO EN REVISION NUMERO 299/2012 INSTAurADA POR EL SINDICATO DE TRABAJADORES PETROLEROS DE LA REPUBLICA MEXICANA DEL INDICE DEL QUINTO TRIBUNAL COLEGIADO DEL CENTRO AUXILIAR DE LA TERCERA REGION CON SEDE EN MORELIA MICHOACAN.', 0.00, 91.00, 0.00, 'Servir como fuente de conocimiento', 'No se consiguio el fuorum necesario', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(43, 43, 1, 4, 1, '2014-09-15 00:00:00', '2014-10-07 00:00:00', 'Direccion General de Capacitacion Promocion y Relaciones Institucionales', 'Camara de diputados', '2013.N.0051', 'IFAI/SPADP/DGV/063/2042', 'No disponible', 'PARTICIPAR EN LA REUNION DE LA REGION NORTE DE LA CONFERENCIA MEXICANA PARA EL ACCESO A LA INFORMACION PUBLICA (COMAIP) REUNION DE LA COMISION DE GESTION DOCUMENTAL TECNOLOGIAS DE LA INFORMACION Y GOBIERNO ABIERTO DE LA CONFERENCIA MEXICANA PARA EL ACCESO A LA INFORMACION PUBLICA (COMAIP) Y EN EL PRIMER FORO NACIONAL DE ANALISIS Y REFLEXION SOBRE LA REFORMA CONSTITUCIONAL EN MATERIA DE TRANSPARENCIA Y ACCESO A LA INFORMACION PUBLICA EN MEXICO ORGANIZADO POR LA CONFERENCIA MEXICANA PARA EL ACCESO A LA INFORMACION PUBLICA (COMAIP).', 86.00, 37.00, 913.00, 'Solucionar problematicas que afectan a la sociedad', 'Se limitaron los tiempos', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(44, 44, 1, 1, 1, '2014-09-16 00:00:00', '2014-10-08 00:00:00', 'Direccion General de Comunicaci', 'Presidencia', '2013.N.0052', 'IFAI/SPADP/DGV/063/2043', 'No disponible', 'COORDINAR LA PARTICIPACION DEL COMISIONADO PRESIDENTE DEL IFAI EN EL FORO NACIONAL DE ANALIS Y REFLEXION SOBRE LA REFORMA CONSTITUCIONAL EN MATERIA DE TRANSPARENCIA Y ACCESO A LA INFORMACION PUBLICA EN MEXICO ORGANIZADA POR LA COMISION ESTATAL PARA LA TRANSPARENCIA Y EL ACCESO A LA INFORMACION PUBLICA DE DurANGO Y LA CONFERENCIA MEXICANA PARA EL ACCESO A LA INFORMACION PUBLICA (COMAIP).', 789.00, 0.00, 375.00, 'Discutir los motivos de la migracion', 'No se obtuvo un retroalimentacion', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(45, 45, 1, 5, 2, '2014-09-01 00:00:00', '2014-09-28 00:00:00', 'Direccion General de Capacitacion Promocion y Relaciones Institucionales', 'Camara de diputados', '2013.N.0053', 'IFAI/SPADP/DGV/063/2044', 'No disponible', 'PARTICIPAR EN LA PRIMERA JORNADA DE CAPACITACION PARA PRESIDENTES MUNICIPALES SOBRE LA IMPORTANCIA DE LA RENDICION DE CUENTAS Y LA TRANSPARENCIA EN LOS MUNICIPIOS ORGANIZADA POR EL INSTITUTO NACIONAL PARA EL FEDERALISMO Y EL DESARROLLO MUNICIPAL Y EL GOBIERNO DEL ESTADO DE PUEBLA.', 100.00, 993.00, 46.00, 'Determinar el origen de la vida', 'Se cancelaron ponencias', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(46, 46, 2, 2, 2, '2014-09-02 00:00:00', '2014-09-29 00:00:00', 'Organo Interno de Control', 'Senado de la republica', '2013.N.0054', 'IFAI/SPADP/DGV/063/2045', 'IFAI/SG/DGCPRI/263/2014', 'PARTICIPAR EN LA REUNION DE COORDINACION CON SERVIDORES PUBLICOS DEL IFAI PARA LA LOGISTICA DE LA XIV ASAMBLEA PLENARIA DE LA CONFERENCIA MEXICANA PARA EL ACCESO A LA INFORMACION PUBLICA (COMAIP)', 0.00, 474.00, 28.00, 'Motivar la creacion de un instituto independiente', 'Antes se deberia de consultar', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(47, 47, 2, 4, 2, '2014-09-03 00:00:00', '2014-09-30 00:00:00', 'Dirreccion General de Capacitacion Promociones y Relaciones Institucionales', 'CFE', '2013.N.0055', 'No disponible', 'IFAI/SG/DGCPRI/263/2015', 'Asistir a la L Reunion Naiconal de la Comision Nacional Permanente de Contralores Estado Federacion', 0.00, 0.00, 0.00, 'Solicitar recursos para el herario', 'Hubo inconsistencias en los discursos', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(48, 48, 1, 3, 1, '2014-09-04 00:00:00', '2014-10-01 00:00:00', 'Direccion General de Capacitacion Promocion y Relaciones Institucionales', 'CFE', '2013.N.0056', 'No disponible', 'IFAI/SG/DGCPRI/263/2016', 'ASISTIR A LA FERIA NACIONAL DEL LIBRO PARA PROMOVER Y DIFUNDIR EL EJERCICIO DEL DERECHO DE ACCESO A LA INFORMACION Y PROTECCION DE DATOS PERSONALES A TRAVES DE LA ORIENTACION ASESORIA Y ENTREGA DE MATERIALES DE DIVULGACION A LAS PERSONAS QUE ASISTAN AL MODULO ITINERANTE DEL CENTRO DE ATENCION A LA SOCIEDAD DEL IFAI QUE SE INSTAurARA EN DICHO EVENTO.', 0.00, 0.00, 0.00, 'Pedir una comision especial', 'No se presentaron los resultados', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(49, 49, 1, 3, 1, '2014-09-05 00:00:00', '2014-10-05 00:00:00', 'Direccion Central de Instituciones', 'Camara de comercio', '2013.N.0057', 'No disponible', 'IFAI/SG/DGCPRI/263/2017', 'PARTICIPAR EN LA REUNION DE COORDINACION CON SERVIDORES PUBLICOS DEL IFAI PARA LA LOGISTICA DE LA XIV ASAMBLEA PLENARIA DE LA CONFERENCIA MEXICANA PARA EL ACCESO A LA INFORMACION PUBLICA (COMAIP)', 0.00, 431.00, 0.00, 'Comunicar los resultados obtenidos', 'No aplica', 'F');
INSERT INTO commissions(id, public_officer_id, id_mec_origen, id_tipo_comision, id_representacion, fechainicio_com, fechafin_com, inst_genera, ur, consecutivo, acuerdo, oficio, motivo, comprobado_total, sin_comprobar_total, viatico_devuelto_total, resultado, observaciones, estatus_comision) VALUES
(50, 50, 2, 3, 1, '2014-09-25 00:00:00', '2014-10-01 00:00:00', 'Canacintra', 'Consejo de comunicaci', '2013.N.0058', 'No disponible', 'IFAI/SG/DGCPRI/263/2018', 'Asistir a la L Reunion Naiconal de la Comision Nacional Permanente de Contralores Estado Federacion', 883.00, 3674.00, 8.00, 'Perseguir a los culpables', 'No aplica', 'F');
