-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.315.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 27/09/2014 02:27:31 p. m.
-- Server version: 5.6.11-log
-- Client version: 4.1

SET NAMES 'utf8';
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(1, 1, '2014-09-18 00:00:00', 1, 1200, 1, 'S', 4);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(2, 2, '2014-09-19 00:00:00', 3, 1236, 1, 'S', 4);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(3, 3, '2014-09-20 00:00:00', 2, 1589, 1, 'S', 4);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(4, 4, '2014-09-21 00:00:00', 1, 2630, 1, 'S', 4);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(5, 5, '2014-09-22 00:00:00', 1, 310, 1, 'S', 4);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(6, 6, '2014-09-23 00:00:00', 3, 1200, 1, 'S', 4);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(7, 7, '2014-09-24 00:00:00', 1, 7562, 1, 'S', 4);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(8, 8, '2014-09-25 00:00:00', 3, 6256, 1, 'S', 4);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(9, 9, '2014-09-26 00:00:00', 1, 546, 1, 'S', 4);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(10, 10, '2014-09-27 00:00:00', 3, 2630, 1, 'S', 4);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(11, 11, '2014-09-28 00:00:00', 2, 310, 1, 'S', 4);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(12, 12, '2014-09-29 00:00:00', 2, 1200, 1, 'S', 4);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(13, 13, '2014-09-30 00:00:00', 1, 7562, 1, 'S', 4);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(14, 14, '2014-10-05 00:00:00', 1, 6256, 1, 'S', 4);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(15, 15, '2014-10-06 00:00:00', 2, 2136, 1, 'S', 4);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(16, 16, '2014-10-08 00:00:00', 1, 2112, 1, 'S', 4);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(17, 17, '2014-09-25 00:00:00', 2, 3201, 1, 'S', 4);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(18, 18, '2014-09-25 00:00:00', 3, 1203, 1, 'N', 3);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(19, 19, '2014-09-27 00:00:00', 3, 310, 1, 'N', 1);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(20, 20, '2014-09-28 00:00:00', 2, 2600, 1, 'N', 3);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(21, 21, '2014-09-29 00:00:00', 1, 1589, 1, 'N', 2);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(22, 22, '2014-09-15 00:00:00', 1, 310, 1, 'N', 2);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(23, 23, '2014-09-16 00:00:00', 1, 1200, 1, 'S', 4);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(24, 24, '2014-09-01 00:00:00', 3, 2600, 1, 'N', 1);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(25, 25, '2014-09-02 00:00:00', 3, 3600, 1, 'S', 4);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(26, 26, '2014-09-24 00:00:00', 2, 1236, 1, 'N', 3);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(27, 27, '2014-09-18 00:00:00', 2, 1589, 1, 'N', 2);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(28, 28, '2014-09-19 00:00:00', 1, 2630, 1, 'N', 1);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(29, 29, '2014-09-20 00:00:00', 1, 310, 2, 'N', 1);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(30, 30, '2014-09-21 00:00:00', 3, 1200, 2, 'S', 4);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(31, 31, '2014-09-22 00:00:00', 2, 1236, 2, 'N', 1);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(32, 32, '2014-09-23 00:00:00', 3, 55132, 2, 'S', 4);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(33, 33, '2014-09-24 00:00:00', 1, 789, 2, 'N', 4);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(34, 34, '2014-09-25 00:00:00', 2, 9120, 2, 'S', 4);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(35, 35, '2014-09-26 00:00:00', 3, 123, 2, 'N', 2);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(36, 36, '2014-09-27 00:00:00', 1, 1266, 2, 'N', 2);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(37, 37, '2014-09-28 00:00:00', 2, 2162, 2, 'S', 4);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(38, 38, '2014-09-29 00:00:00', 3, 2621, 2, 'S', 4);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(39, 39, '2014-09-30 00:00:00', 1, 126, 2, 'S', 4);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(40, 40, '2014-09-24 00:00:00', 2, 100, 2, 'N', 1);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(41, 41, '2014-09-25 00:00:00', 3, 1200, 2, 'S', 4);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(42, 42, '2014-09-25 00:00:00', 1, 1200, 2, 'S', 4);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(43, 43, '2014-09-26 00:00:00', 1, 1200, 2, 'S', 4);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(44, 44, '2014-09-27 00:00:00', 3, 7562, 2, 'S', 4);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(45, 45, '2014-09-28 00:00:00', 2, 55132, 2, 'S', 4);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(46, 46, '2014-10-03 00:00:00', 3, 6256, 2, 'S', 4);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(47, 47, '2014-10-04 00:00:00', 1, 55132, 2, 'S', 4);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(48, 48, '2014-10-05 00:00:00', 3, 310, 2, 'S', 4);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(49, 49, '2014-10-06 00:00:00', 1, 7562, 2, 'N', 1);
INSERT INTO ifai.gasto(idGasto, idViaje, FECHA_COMPROBANTE, idConcepto, IMPORTE_COMPROBANTE, idMoneda, EXISTE_COMPROBANTE, idJustificacion) VALUES
(50, 50, '2014-10-07 00:00:00', 2, 122, 2, 'N', 3);
