
INSERT INTO `tema_de_viaje_catalogos` VALUES (1,'POLITICAS DE ACCESO A LA INFORMACION');
INSERT INTO `tema_de_viaje_catalogos` VALUES (2,'ASUNTOS INTERNACIONALES');
INSERT INTO `tema_de_viaje_catalogos` VALUES (3,'NORMATIVA DE ACCESO A LA INFORMACION');
INSERT INTO `tema_de_viaje_catalogos` VALUES (4,'CAPACITACION Y CULTURA DE LA TRANSPARENCIA');
INSERT INTO `tema_de_viaje_catalogos` VALUES (5,'GESTION DOCUMENTAL DE ARCHIVOS');
INSERT INTO `tema_de_viaje_catalogos` VALUES (6,'INDICADORES Y EVALUACION');
INSERT INTO `tema_de_viaje_catalogos` VALUES (7,'NORMATIVIDAD DE DATOS PERSONALES');
INSERT INTO `tema_de_viaje_catalogos` VALUES (8,'SUPERVISION VIGILANCIA VERIFICACION Y SANCIONES');
INSERT INTO `tema_de_viaje_catalogos` VALUES (9,'TECNOLOGIAS DE LA INFORMACION');
INSERT INTO `tema_de_viaje_catalogos` VALUES (10,'GOBIERNO ABIERTO Y TRANSPARENCIA');
INSERT INTO `tema_de_viaje_catalogos` VALUES (11,'VINCULACION CON ESTADOS Y MUNICIPIOS');
INSERT INTO `tema_de_viaje_catalogos` VALUES (12,'VINCULACION CON NUEVOS SUJETOS OBLIGADOS');
INSERT INTO `tema_de_viaje_catalogos` VALUES (13,'VINCULACION Y PROMOCION DEL DERECHO');

