
INSERT INTO `unidad_adms` VALUES (1,' COMISIONADO');
INSERT INTO `unidad_adms` VALUES (2,' DIRECCION GENERAL DE ADMINISTRACION');
INSERT INTO `unidad_adms` VALUES (3,' DIRECCION GENERAL DE ANALISIS NORMATIVO Y EVALUACION DE LA INFORMACION');
INSERT INTO `unidad_adms` VALUES (4,' DIRECCION GENERAL DE ASUNTOS INTERNACIONALES');
INSERT INTO `unidad_adms` VALUES (5,' DIRECCION GENERAL DE ASUNTOS JURIDICOS');
INSERT INTO `unidad_adms` VALUES (6,' DIRECCION GENERAL DE AUTORREGULACION');
INSERT INTO `unidad_adms` VALUES (7,' DIRECCION GENERAL DE CAPACITACION  PROMOCION Y RELACIONES INSTITUCIONALES');
INSERT INTO `unidad_adms` VALUES (8,' DIRECCION GENERAL DE COMUNICACION SOCIAL Y DIFUSION');
INSERT INTO `unidad_adms` VALUES (9,' DIRECCION GENERAL DE COORDINACION DE POLITICAS DE ACCESO');
INSERT INTO `unidad_adms` VALUES (10,' DIRECCION GENERAL DE COORDINACION Y VIGILANCIA DE LA ADMINISTRACION PUBLICA FEDERAL');
INSERT INTO `unidad_adms` VALUES (11,' DIRECCION GENERAL DE GESTION DE LA INFORMACION Y ESTUDIOS');
INSERT INTO `unidad_adms` VALUES (12,' DIRECCION GENERAL DE NORMATIVIDAD CONSULTA Y ATENCION REGIONAL');
INSERT INTO `unidad_adms` VALUES (13,' DIRECCION GENERAL DE SUSTANCIACION Y SANCION');
INSERT INTO `unidad_adms` VALUES (14,' DIRECCION GENERAL DE TECNOLOGIAS DE LA INFORMACION');
INSERT INTO `unidad_adms` VALUES (15,' DIRECCION GENERAL DE VERIFICACION');
INSERT INTO `unidad_adms` VALUES (16,' PLENO');
INSERT INTO `unidad_adms` VALUES (17,' SECRETARIA DE ACCESO A LA INFORMACION');
INSERT INTO `unidad_adms` VALUES (18,' SECRETARIA DE PROTECCION DE DATOS PERSONALES');
INSERT INTO `unidad_adms` VALUES (19,' SECRETARIA GENERAL');
INSERT INTO `unidad_adms` VALUES (20,' SECRETARIA TECNICA DEL PLENO');

