INSERT INTO `tipo_comisions` VALUES (1,'RECIBIR CAPACITACION\r');
INSERT INTO `tipo_comisions` VALUES (2,'IMPARTIR CAPACITACION\r');
INSERT INTO `tipo_comisions` VALUES (3,'PARTICIPACION EN EVENTO PUBLICO\r');
INSERT INTO `tipo_comisions` VALUES (4,'NOTIFICACION\r');
INSERT INTO `tipo_comisions` VALUES (5,'VERIFICACION\r');