
INSERT INTO `tipo_comisions` VALUES (1,'RECIBIR CAPACITACION');
INSERT INTO `tipo_comisions` VALUES (2,'IMPARTIR CAPACITACION');
INSERT INTO `tipo_comisions` VALUES (3,'PARTICIPACION EN EVENTO PUBLICO');
INSERT INTO `tipo_comisions` VALUES (4,'NOTIFICACION');
INSERT INTO `tipo_comisions` VALUES (5,'VERIFICACION');

