
INSERT INTO `justificacion_catalogos` VALUES (1,'EL PROVEEDOR DEL SERVICIO DE ALIMENTOS ES PEQUEÑO CONTRIBUYENTE Y SOLO EXPIDE COMPROBANTES EN OPERACIONES SUPERIORES A $100.00 PESOS M.N.');
INSERT INTO `justificacion_catalogos` VALUES (2,'EN LA LOCALIDAD NO EXISTEN PRESTADORES DE SERVICIOS DE HOSPEDAJE QUE EXPIDAN COMPROBANTES FISCALES.');
INSERT INTO `justificacion_catalogos` VALUES (3,'EL PRESTADOR DE SERVICIOS DE TRANSPORTE LOCAL (TAXI CAMION COMBI) ES PEQUEÑO CONTRIBUYENTE NO EXPIDE COMPROBANTES.');

