
INSERT INTO `justificacion_catalogos` VALUES (1,'\rEL PROVEEDOR DEL SERVICIO DE ALIMENTOS ES PEQUEÑO CONTRIBUYENTE Y SOLO EXPIDE COMPROBANTES EN OPERACIONES SUPERIORES A $100.00 PESOS M.N.\r');
INSERT INTO `justificacion_catalogos` VALUES (2,'\rEN LA LOCALIDAD NO EXISTEN PRESTADORES DE SERVICIOS DE HOSPEDAJE QUE EXPIDAN COMPROBANTES FISCALES.\r');
INSERT INTO `justificacion_catalogos` VALUES (3,'\rEL PRESTADOR DE SERVICIOS DE TRANSPORTE LOCAL (TAXI CAMION COMBI) ES PEQUEÑO CONTRIBUYENTE NO EXPIDE COMPROBANTES.\r');

